### ISSUE TITLE
Roadmap to 2.2.0

### ISSUE THREAD

**Issue by Indigo744** [neveldo/jQuery-Mapael#338]
@neveldo 

Can we list the remaining features / tasks needed for the release of 2.2.0?
- [ ] Fix #361 
- [x] Review/Merge PR #337 
- [x] Review/Merge PR #344 
- [ ] Implements #253/Review/Merge PR #352 
- [x] Fix #346/Review/Merge PR neveldo/mapael-maps#44
- [ ] Implements `zoomOnCLick`/Review/Merge PR (TBD)
- [x] Update Changelog ([in progress](https://github.com/neveldo/jQuery-Mapael/blob/update-changelog/CHANGELOG.md))
- [x] Update documentation ([in progress](https://github.com/neveldo/mapael-documentation/pull/9))

~~Also, should we implement #276 for 2.2.0?~~

Regarding the mapael-maps repo, should it follow the mapael repo version or should it have its own numbering?

**Comment by neveldo** [comment]
Hi,

This roadmap looks very good for the version 2.2.0 ! I think that #253 should be more prioritary than #337 if we stricly consider the number of requests from the users, but it seems that you are already working to resolve #276 !

Have you already begin to work on the changelog or documentation ? Maybe I can help on this parts ... (sorry for not helping you more on code itself and the features, I have quite few free time at the moment...)

**Comment by Indigo744** [comment]
Sorry I mixed up the PR number! I am actually working on #253 and plan to land the PR soon. As you said, a lot of people were asking for this feature. 

#276 is actually more complicated than previously though. We will need some more discussion there.

I've added #340 to clean up some bbox codes.

**Comment by neveldo** [comment]
Ok for the  changelog/documentation part, I will make some PRs soon, probably in the next few days :)

Ok for https://github.com/neveldo/jQuery-Mapael/issues/276 , it will bring a higly requested feature !

Thanks for having added #340, I was just  editing the roadmap, but you have been quicker than me ;)

**Comment by Indigo744** [comment]
Alright! Hopefully our modifications didn't collide :)

But I think you meant #253 (plot size reduction), right? So much different numbers....

Also, what about the mapael-maps repo? Should we follow Mapael releases?

**Comment by neveldo** [comment]
What would be the advantages of following the same versions between the two projects ?

NB : For now, I didn't tagged any version on the mapael-maps repository.

Even if the two repositories are tightly related, I think that they could be versionned independently from each other. For instance, we could release a new major version of mapael-maps if we needed to bring some non-backward compatible changes to them in order to work properly with a new major version of jquery mapael (we can still add a note into the readme to mention the compatibility with the version(s)  of mapael). We could tag a minor version whenever we add a new map, and a patch version for a fix on a particular map. What do you think ?

Moreover, maybe the mapael-maps repository should be available through NPM (and why not on cdnjs ? (mapael is already on cdnjs, but they didn't added mapael-maps despite I asked them to :( )

**Comment by Indigo744** [comment]
Regarding CDNJS, it's ongoing I think, see #270 

I think you are right. However, we may need to tag version more regularly (and generate minified version), like after adding a map.

**Comment by neveldo** [comment]
But the PR is open since more than one year, I have ask for some news on it !

**Comment by neveldo** [comment]
Hello @Indigo744 ,

I'm thinking about some other features for the next release.

- Since you have added options to zoom-in ona specific area or plot, I think it could be interresting to have an option such as "zoomOnCLick : true|false" for areas and plot ! What do you think ?

- The more I think about it, the more I wonder if supporting GeoJson wouldn't be a "killer feature" ! I need to find some time to dive into the format (I confess, I don't know much about it for now).

- I wonder if we couldn't provide a way to set a CSV file as source to generate plots or areas ? I think it could ease the creation of choropleths. As you can see in https://www.vincentbroute.fr/mapael/try.html , it takes a very few lines of code to convert a CSV to a mapael-compatible collection of plots or areas properties. We could for instance set a conf like this : 

```
{
    (...)
   "plots": {
      "csv": "http://www.(...).com/data/plots.csv",
      "separator": ",",
      "enclosure": "\"",
    },
    (...)
}
```

**Comment by Indigo744** [comment]
Love your ideas! However, should we really add these for 2.2.0? Or do you mean 2.3.0?

**Comment by neveldo** [comment]
You're right, the last two could take a long time to achieve ! However, the first one could be easy to add I think as the hard part is already done ! :)

**Comment by Indigo744** [comment]
Agreed. I'll make a PR for the first part. Should we open a new issue for discussing and scoping 2.3.0?

**Comment by neveldo** [comment]
Hello @Indigo744 ,

What do you think about extending this thread with the roadmap for all the  next minor releases of Mapael, and discussions about the features & patchs to include in each of them ? And we could use the other thread https://github.com/neveldo/jQuery-Mapael/issues/345 to discuss about the big changes for the next major releases.
Or maybe you prefer to split the discussions for each version into several threads ? (I have no preference for my part)

**Comment by Indigo744** [comment]
IMHO a thread per version would be better. Hence we can list the tasks and users have a clear view of the remaining work. When a version is out, we can close this thread so it will not be a burder anymore. We don't have a lot of version anyway, so we are not talking about hundred threads ^^

**Comment by neveldo** [comment]
Alright for me !

**Comment by neveldo** [comment]
Hello @Indigo744,

FYI, I have started to write on the changelog for the version 2.2.0 : https://github.com/neveldo/jQuery-Mapael/blob/update-changelog/CHANGELOG.md , without surprise, you are the main craftsman of this upcoming new version :)

**Comment by Indigo744** [comment]
Just saw you released the 2.2.0 version. Nice! Thanks. It's a major milestone, with some nice improvements. 

Looking back at the todolist, I can see that I left quite a lot of point open... I'm sorry for that 😞 

Maybe we should start a "roadmap to 2.3.0" with the leftovers. I'll try to continue the work when I have more time...

**Comment by neveldo** [comment]
Hello @Indigo744 ,

I'm glad to hear from you ! Thanks, most of these improvements come from you. Indeed, I published the 2.2.0 version in order to make our last improvements available to the users !

Don't worry, we have all the time to work on the remaining (and the next) ones for the next milestone :) . You are right, it's a good idea to start a new roadmap for the 2.3.0.

**Comment by andersonreloaded** [comment]
Hi Folks,

Thank you for the effort and the release.
However, was expecting updates for #253 and #352.
Hope to see it soon :-)

**Comment by Indigo744** [comment]
@andersonreloaded I'm really sorry that I haven't finish this PR for 2.2.0. You know, sometime life gets in the way... But thanks for the reminder. I'll try to find some time this week. Stay tuned 😉

**Comment by Indigo744** [comment]
@neveldo could you create a roadmap for 2.3.0 so we have a clear view of the work needed? Thanks 😺

**Comment by neveldo** [comment]
Hi @andersonreloaded , @Indigo744 ,

Ok, I will create the roadmap for 2.3.0 asap in the next few days !

**Comment by neveldo** [comment]
Here we go ! https://github.com/neveldo/jQuery-Mapael/issues/382

**Comment by andersonreloaded** [comment]
Guys! Any updates :-)

**Comment by neveldo** [comment]
Hi @andersonreloaded , I'm glad you get interest into jQuery Mapael ! At the moment, I'm working on some other projets , so I haven't planned to work on the next version shortly. I think that Mapael deserve an overal update (dependencies update, etc), as there haven't been new tags since a while now. As it's an opensource project, I would be very glad to validate new improvements for  the lib, maybe you want to contribute to the project ?
