### ISSUE TITLE
Roadmap to 2.3.0

### ISSUE THREAD

**Issue by neveldo** [neveldo/jQuery-Mapael#382]
**Roadmap to 2.3.0 :**

- [ ] Fix #361 
- [ ] Implements #253/Review/Merge PR #352 
- [ ] Implements `zoomOnCLick` option on areas/plot that allows to zoom on a specific map element when the user click on it
- [ ] Update Changelog ([todo](https://github.com/neveldo/jQuery-Mapael/blob/update-changelog/CHANGELOG.md))
- [ ] Update documentation ([todo](https://github.com/neveldo/mapael-documentation/pull/9))
- [ ] (?) Version the mapael-maps repository and make it available through a NPM package

cc @Indigo744
